title: My music blog
author: Jessica
email: an.email@email.mail
description: > # this means to ignore newlines until "baseurl:"
 A fun blog about music.
theme: minima

# social links
twitter_username: @twitter
github_username:  @jess-ica

show_excerpts: true # set to false to remove excerpts on the homepage
